# Generated by Django 5.0.4 on 2024-04-19 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PredictorApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
